### ISSUE TITLE
VM execution error.. Data: Just (String \"Bad instruction fe\")

### ISSUE THREAD

**Issue by ensrationis** [akru/xrtd#4]
15:46:46 [INFO] "CallException JSON-RPC error -32015: VM execution error.. Data: Just (String \"Bad instruction fe\")"
15:46:46 [INFO] "Member 0xbc0503993c670ee99c7301cb71c4c50d0d0f3d71 k(6373276) t(50) b(6373276)"
15:46:49 [INFO] "BALANCE :: 30.600768971 XRT : 53.43724664501156 ether"
15:46:59 [INFO] "BALANCE :: 30.600768971 XRT : 53.43724664501156 ether"
15:47:01 [INFO] "CallException JSON-RPC error -32015: VM execution error.. Data: Just (String \"Bad instruction fe\")"
15:47:01 [INFO] "Member 0xbc0503993c670ee99c7301cb71c4c50d0d0f3d71 k(6373276) t(50) b(6373278)"
15:47:09 [INFO] "BALANCE :: 30.600768971 XRT : 53.43724664501156 ether"
15:47:16 [INFO] "CallException JSON-RPC error -32015: VM execution error.. Data: Just (String \"Bad instruction fe\")"
15:47:16 [INFO] "Member 0xbc0503993c670ee99c7301cb71c4c50d0d0f3d71 k(6373276) t(50) b(6373280)"
15:47:19 [INFO] "BALANCE :: 30.600768971 XRT : 53.43724664501156 ether"
15:47:29 [INFO] "BALANCE :: 30.600768971 XRT : 53.43724664501156 ether"
15:47:31 [INFO] "CallException JSON-RPC error -32015: VM execution error.. Data: Just (String \"Bad instruction fe\")"
15:47:31 [INFO] "Member 0xbc0503993c670ee99c7301cb71c4c50d0d0f3d71 k(6373276) t(50) b(6373281)"
15:47:39 [INFO] "BALANCE :: 30.600768971 XRT : 53.43724664501156 ether"
15:47:47 [INFO] "CallException JSON-RPC error -32015: VM execution error.. Data: Just (String \"Bad instruction fe\")"
15:47:47 [INFO] "Member 0xbc0503993c670ee99c7301cb71c4c50d0d0f3d71 k(6373276) t(50) b(6373282)"
15:47:49 [INFO] "BALANCE :: 30.600768971 XRT : 53.43724664501156 ether"
15:47:59 [INFO] "BALANCE :: 30.600768971 XRT : 53.43724664501156 ether"
15:48:02 [INFO] "CallException JSON-RPC error -32015: VM execution error.. Data: Just (String \"Bad instruction fe\")"
15:48:02 [INFO] "Member 0xbc0503993c670ee99c7301cb71c4c50d0d0f3d71 k(6373276) t(50) b(6373284)"
15:48:09 [INFO] "BALANCE :: 30.600768971 XRT : 53.43724664501156 ether"

**Comment by akru** [comment]
Please describe a problem.
